services:
  - type: web
    name: frontend-ui-quickcook
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sprint1-backend-u1ka.onrender.com
      - key: REACT_APP_ENV
        value: production
